version: '3.9'
services:
  api:
    build: .
    image: carsapi
    container_name: api
    ports:
      - "5563:8080"
    depends_on:
      - db

  db:
    container_name: db
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - 5563:1433
    volumes:
      - data:/var/lib/mssqlql
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Examen1234*
      - MSSQL_PID=Developer
      - MSSQL_USER=SA
      - MSSQL_TCP_PORT=1433

volumes:
   data: {}